### ISSUE TITLE
Component doesn't allow multiple instances on the same page

### ISSUE THREAD

**Issue by letithappen** [anthkris/adapt-game-frame#1]
Don't know if there is some other reason for not allowing multiple instances of the adapt-game-frame component.
Using a component attribute _IsFired with "fired = this.model.get('_isFired')" before https://github.com/anthkris/adapt-game-frame/blob/master/js/adapt-game-frame.js#L49 and setting it to true inside or after the "once" function would allow to separate the component behavior between instances allowing the use of multiple instances with different src or data.

**Comment by anthkris** [comment]
Merged this in! We'll see if it works!
